### ISSUE TITLE
H1: Agregar estilos al login igual al prototipo inicial y que sea responsive

### ISSUE THREAD

**Issue by lili14gon** [mi19her/LIM010-data-lovers#6]

**Comment by mi19her** [comment]
1: Iniciar el diseño de colores en CSS, con el tipo de letra y familia.
2: Agregar una imagen de fondo en el body referido al tema.

**Comment by mi19her** [comment]
utilizar el display Flex para ordenar el formulario y centrar el contenido
guiarse del prototipado en mobile para el tamaño del formulario y sus items
